name = "Egregious Industrialization"
author = "esoterica"
version = "0.3.0a1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eac69526db4b5005c36da2d5bc19446ce15ee7fabda818b57acb15f9ee567152"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
