name = "Egregious Industrialization"
author = "esoterica"
version = "0.1.1_ALPHA.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a19b0944900ea336aa437c00d93581b3a4a0b1a3eedcab79b4f2a6dec64e7e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
