name = "Egregious Industrialization"
author = "esoterica"
version = "0.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c30caf562a2b97f8466fbe2bdd2344992b8f9cf944548204c09a298ba9f3147a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
