name = "Egregious Industrialization"
author = "esoterica"
version = "0.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a7ee18a3f6166497d3d64e1bc171d0464ff3c367ae20d50a91b9466619ca9c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
