name = "Egregious Industrialization"
author = "esoterica"
version = "0.1.2_ALPHA.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f102aacc1f90639bb90eb925c18ee81b59bf1b6d0ee7d5d4446012e98593b3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
