name = "Egregious Industrialization"
author = "esoterica"
version = "0.1.1_ALPHA.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39d1521bf398750b262902f032c955819bb2622f5a360d4044864f8aa709ccc2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
