name = "Egregious Industrialization"
author = "esoterica"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b7aa73762bf9d32a3e42691e4d53c4a6f921939a9966f0c1f9156f2acbf069"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
