name = "Egregious Industrialization"
author = "esoterica"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6595ebf45088de789af43c03659133f512a0eeac55ac26cf80769e71650147f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
