name = "Egregious Industrialization"
author = "esoterica"
version = "0.1.2_ALPHA.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76a287b89597cc32a0a6110806cba8c02734985bcba40009c0f12a8239220c74"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
