name = "Egregious Industrialization"
author = "esoterica"
version = "0.1.1_ALPHA.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc591e4fffaab18ff16a882c452c99b0ff3e361335d1b82577f40ffad7340665"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
