name = "Egregious Industrialization"
author = "esoterica"
version = "0.3.0a1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf038967d7bc3b328549224e2b0f1067433380287088b6bd0d89dbe638aee544"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
