name = "Egregious Industrialization"
author = "esoterica"
version = "0.2.0a1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52f41d7f198ad02a1fc96b67e79276d0f96cbaf3c4504574026795d749988d09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21"]
