#General settings
[general]
	#Hide HUD when taking screenshot
	hideHud = true
	#Scale HUD when taking screenshot
	scaleHud = false
	#Width of the screenshot
	# Default: 3840
	# Range: > 0
	width = 7680
	#Height of the screenshot
	# Default: 2160
	# Range: > 0
	height = 4320
	#Delay before taking screenshot
	# Default: 3
	# Range: 0 ~ 10
	delay = 3
	#Save format of the screenshot
	#Allowed Values: PNG, JPG
	saveFormat = "PNG"
