#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 18 17:25:43 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1.zip
