worldgen:
  oreVeins:
    # The grid size (in chunks) for ore vein generation
    # Default: 3
    oreVeinGridSize: 3

    # The maximum random offset (in blocks) from the grid for generating an ore vein.
    # Default: 12
    oreVeinRandomOffset: 12

    # Prevents regular vanilla ores from being generated outside GregTech ore veins
    # Default: true
    removeVanillaOreGen: true

    # Prevents vanilla's large ore veins from being generated
    # Default: true
    removeVanillaLargeOreVeins: true

    # Sets the maximum number of chunks that may be cached for ore vein generation.
    # Higher values may improve world generation performance, but at the cost of more RAM usage.
    # If you substantially increase the ore vein grid size, random vein offset, or have very large (custom) veins, you may need to increase this value as well.
    # Default: 512 (requires restarting the server / re-opening the world)
    oreGenerationChunkCacheSize: 512

    # Sets the maximum number of chunks for which ore indicators may be cached.
    # If you register any custom veins with very large indicator ranges (or modify existing ones that way), you may need to increase this value.
    # Default: 2048 (requires restarting the server / re-opening the world)
    oreIndicatorChunkCacheSize: 2048

# Config options for Mod Compatibility
compat:
  # Config options regarding GTMOGS compatibility with minimap mods
  minimap:
    # Toggle specific map mod integration on/off (need to restart for this to take effect)
    toggle:
      # FTB Chunks integration enabled
      ftbChunksIntegration: true

      # Journey Map integration enabled
      journeyMapIntegration: true

      # Xaero's map integration enabled
      xaerosMapIntegration: true

    # The radius, in blocks, that clicking an ore block will search for veins in.
    # -1 to disable
    # Default: 24
    oreBlockProspectRange: 24

    # The map scale at which displayed ores will stop scaling.
    oreScaleStop: 1.0

    # The size, in pixels, of ore icons on the map
    oreIconSize: 32

    # The string prepending ore names in the ore vein tooltip
    oreNamePrefix: -

    # The color to draw a box around the ore icon with.
    # Accepts either an ARGB hex color prefixed with # or the string 'material' to use the ore's material color
    borderColor: #00000000

    # Which part of the screen to anchor buttons to
    # Default: "BOTTOM_LEFT"
    # Allowed values:
    # - TOP_LEFT
    # - TOP_CENTER
    # - TOP_RIGHT
    # - RIGHT_CENTER
    # - BOTTOM_RIGHT
    # - BOTTOM_CENTER
    # - BOTTOM_LEFT
    # - LEFT_CENTER
    buttonAnchor: BOTTOM_LEFT

    # Which direction the buttons will go
    # Default: "VERTICAL"
    # Allowed values:
    # - VERTICAL
    # - HORIZONTAL
    direction: VERTICAL

    # How horizontally far away from the anchor to place the buttons
    # Default: 20
    xOffset: 20

    # How vertically far away from the anchor to place the buttons
    # Default: 0
    yOffset: 0

dev:
  # Debug general events? (will print recipe conficts etc. to server's debug.log)
  # Default: false
  debug: false

  # Debug ore vein placement? (will print placed veins to server's debug.log)
  # Default: false (no placement printout in debug.log)
  debugWorldgen: false

  # Generate ores in superflat worlds?
  # Default: false
  doSuperflatOres: false

  # Dump all registered GT models/blockstates/etc?
  # Default: false
  dumpAssets: false

