name: packwiz export
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Build what"
        required: true
        default: "build-all"
        type: choice
        options:
          - build-client
          - build-server
          - build-all
      version:
        description: "Version"
        required: true
        default: "DevBuild"
        type: string
  workflow_call:
    inputs:
      target:
        required: true
        default: "build-all"
        type: string
      version:
        required: true
        type: string

jobs:
  pack_pr:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Pack PR
    runs-on: ubuntu-22.04
    concurrency:
      group: pack_pr-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.17.0"
      - run: go install github.com/packwiz/packwiz@latest
      - name: Pack Client
        if: ${{ inputs.target == 'build-client' || inputs.target == 'build-all' }}
        run: |
          packwiz curseforge export -s client
            - name: Pack Client
      - name: Pack Server
        if: ${{ inputs.target == 'build-server' || inputs.target == 'build-all' }}
        run: |
          packwiz curseforge export -s server

        shell: bash
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-zipzip
          path: ./*.zip
          if-no-files-found: error
          overwrite: true
          compression-level: 0
